id: P08868FC3
initial_creation_type: input
source_metadata:
  title: Tilopa
  language: zh
  description: 'Texts by and about the great siddha Tilopa (ti lo pa, 988–1069):'
  volume:
    ee1f125a9918488aaaff080a1c6e6b6d:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
created_at: '2022-03-01T02:25:12.716138'
last_modified_at: '2022-03-01T02:25:12.716141'
